### ISSUE TITLE
Website contains harmful warning

### ISSUE THREAD

**Issue by LabsupportEvert** [solo-fsw/eprime_package_markers#5]
When I'm trying to download the software there's an message that in Firefox that the website contains harmful programs.

 
![afbeelding](https://github.com/solo-fsw/eprime_package_markers/assets/98744988/f98bbe0c-95c2-4be0-879e-aa30e020516a)

**Comment by spruitim** [comment]
Replaced DownGit with https://download-directory.github.io/ for downloading folders and the software.
